import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, ImagePlus, LogOut, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import type { User } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

type Story = Database["public"]["Tables"]["stories"]["Row"];
export const Route=createFileRoute("/admin")({head:()=>({meta:[{title:"Studio Manager | theSafira"},{name:"description",content:"Private portfolio management for theSafira."},{property:"og:title",content:"theSafira Studio Manager"},{property:"og:description",content:"Private portfolio management."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Admin});

function Admin(){const[user,setUser]=useState<User|null>(null);const[admin,setAdmin]=useState(false);const[loading,setLoading]=useState(true);const[stories,setStories]=useState<Story[]>([]);const[status,setStatus]=useState("");
  async function refresh(){const{data:{user}}=await supabase.auth.getUser();setUser(user);if(user){const{data}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();setAdmin(Boolean(data));if(data){const{data:rows}=await supabase.from("stories").select("*").order("created_at",{ascending:false});setStories(rows??[])}}setLoading(false)}
  useEffect(()=>{refresh();const{data}=supabase.auth.onAuthStateChange(()=>refresh());return()=>data.subscription.unsubscribe()},[]);
  async function google(){await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin+"/admin"})}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const title=String(f.get("title"));const{error}=await supabase.from("stories").insert({title,slug:String(f.get("slug")),category:String(f.get("category")),location:String(f.get("location")),cover_image:String(f.get("cover_image")),description:String(f.get("description")),published:false});setStatus(error?error.message:"Story saved as a draft.");if(!error){e.currentTarget.reset();refresh()}}
  async function upload(file:File){const safe=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,"-")}`;const{error}=await supabase.storage.from("portfolio-media").upload(safe,file);setStatus(error?error.message:"Photograph uploaded securely. Add it to a story from its media record.")}
  if(loading)return <main className="grid min-h-screen place-items-center bg-ink text-paper">Opening the studio…</main>;
  if(!user)return <main className="grid min-h-screen place-items-center bg-ink px-6 text-paper"><div className="w-full max-w-md border-t border-paper/30 py-10 text-center"><p className="font-display text-5xl">theSafira</p><h1 className="mt-10 text-3xl">Studio manager</h1><p className="mt-3 text-sm text-paper/55">Sign in to manage photographs and stories.</p><Button onClick={google} variant="editorialOutline" size="editorial" className="mt-8">Continue with Google</Button><Link to="/" className="mt-8 flex items-center justify-center gap-2 text-xs"><ArrowLeft className="size-4"/>Return to portfolio</Link></div></main>;
  if(!admin)return <main className="grid min-h-screen place-items-center px-6"><div className="max-w-lg text-center"><h1 className="text-5xl">Set up your studio</h1><p className="mt-5 text-sm leading-7 text-muted-foreground">If this is the first studio account, claim administrator access to begin managing the portfolio.</p><div className="mt-7 flex justify-center gap-3"><Button variant="editorial" onClick={async()=>{const{error}=await supabase.from("user_roles").insert({user_id:user.id,role:"admin"});setStatus(error?error.message:"Studio access ready.");if(!error)refresh()}}>Claim studio access</Button><Button variant="outline" onClick={()=>supabase.auth.signOut()}>Sign out</Button></div>{status&&<p className="mt-4 text-xs text-muted-foreground">{status}</p>}</div></main>;
  return <main className="min-h-screen"><header className="flex items-center justify-between border-b border-border px-6 py-5 lg:px-12"><div><p className="font-display text-3xl">theSafira</p><p className="text-[10px] uppercase tracking-[.18em] text-muted-foreground">Studio manager</p></div><Button variant="ghost" size="icon" aria-label="Sign out" onClick={()=>supabase.auth.signOut()}><LogOut/></Button></header><div className="mx-auto grid max-w-[1400px] gap-16 px-6 py-14 lg:grid-cols-[1fr_.65fr] lg:px-12"><section><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-muted-foreground">Portfolio</p><h1 className="mt-2 text-6xl">Stories</h1></div><label className="cursor-pointer"><input type="file" accept="image/*" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/><span className="inline-flex h-10 items-center gap-2 border border-border px-4 text-xs uppercase"><ImagePlus className="size-4"/>Upload photo</span></label></div><div className="mt-10 border-t border-border">{stories.length?stories.map(s=><div key={s.id} className="flex items-center justify-between border-b border-border py-5"><div><h2 className="font-sans text-base">{s.title}</h2><p className="mt-1 text-xs text-muted-foreground">{s.location} · {s.published?"Published":"Draft"}</p></div></div>):<p className="py-10 text-sm text-muted-foreground">No studio stories yet. Add your first one.</p>}</div></section><section><p className="text-[10px] uppercase tracking-[.18em] text-muted-foreground">New story</p><h2 className="mt-2 text-4xl">Create a draft</h2><form onSubmit={create} className="mt-8 grid gap-5">{[["title","Title"],["slug","Web address"],["category","Category"],["location","Location"],["cover_image","Cover image URL"]].map(([name,label])=><label key={name} className="text-xs">{label}<input required name={name} className="mt-2 h-11 w-full border border-input bg-transparent px-3 outline-none focus:border-foreground"/></label>)}<label className="text-xs">Description<textarea name="description" rows={4} className="mt-2 w-full border border-input bg-transparent p-3 outline-none focus:border-foreground"/></label><Button type="submit" variant="editorial" size="editorial"><Plus/>Save draft</Button>{status&&<p className="text-xs text-muted-foreground">{status}</p>}</form></section></div></main>}