import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { stories } from "@/lib/portfolio-data";

export const Route = createFileRoute("/stories/$slug")({
  head: ({ params }) => { const s = stories.find(x=>x.slug===params.slug); return { meta: [{title:`${s?.title ?? "Story"} | theSafira`},{name:"description",content:`${s?.category ?? "Photography"} story photographed by theSafira in ${s?.location ?? "India"}.`},{property:"og:title",content:`${s?.title ?? "Story"} | theSafira`},{property:"og:description",content:"An honest, cinematic photographic story."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}; },
  component: StoryPage,
});
function StoryPage(){ const {slug}=Route.useParams(); const story=stories.find(s=>s.slug===slug) ?? stories[0]; const gallery=[story.image,...stories.filter(s=>s.slug!==slug).map(s=>s.image),story.image]; const [open,setOpen]=useState<number|null>(null); useEffect(()=>{const key=(e:KeyboardEvent)=>{if(open===null)return;if(e.key==="Escape")setOpen(null);if(e.key==="ArrowRight")setOpen((open+1)%gallery.length);if(e.key==="ArrowLeft")setOpen((open-1+gallery.length)%gallery.length)};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[open,gallery.length]); return <main className="bg-paper"><section className="relative min-h-[90vh] text-paper"><img src={story.image} alt={story.title} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-ink/35"/><Link to="/" className="absolute left-6 top-7 z-10 flex items-center gap-2 text-xs uppercase tracking-[.16em]"><ArrowLeft className="size-4"/>theSafira</Link><div className="absolute inset-x-6 bottom-12 z-10 lg:inset-x-12"><p className="text-xs uppercase tracking-[.2em]">{story.category} · {story.location}</p><h1 className="mt-4 text-7xl md:text-9xl">{story.title}</h1></div></section><section className="mx-auto max-w-4xl px-6 py-28 text-center"><p className="font-display text-4xl leading-tight md:text-6xl">A day made not only of rituals, but of the glances and gestures that lived quietly between them.</p><p className="mt-8 text-xs uppercase tracking-[.2em] text-muted-foreground">{story.date} · {story.location}</p></section><section className="grid grid-cols-12 gap-3 pb-20">{gallery.map((img,i)=><button key={i} onClick={()=>setOpen(i)} className={`${i===0||i===3?"col-span-12 aspect-[16/9]":"col-span-6 aspect-[4/5]"} overflow-hidden`} aria-label={`Open image ${i+1}`}><img src={img} alt={`${story.title} photograph ${i+1}`} loading="lazy" className={`h-full w-full object-cover ${i===3?"grayscale":""}`}/></button>)}</section>{open!==null&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-ink text-paper"><img src={gallery[open]} alt={`${story.title} enlarged photograph`} className="max-h-[92vh] max-w-[92vw] object-contain"/><Button variant="ghost" size="icon" className="absolute right-5 top-5" onClick={()=>setOpen(null)} aria-label="Close"><X/></Button><Button variant="ghost" size="icon" className="absolute left-5" onClick={()=>setOpen((open-1+gallery.length)%gallery.length)} aria-label="Previous"><ChevronLeft/></Button><Button variant="ghost" size="icon" className="absolute right-5" onClick={()=>setOpen((open+1)%gallery.length)} aria-label="Next"><ChevronRight/></Button><span className="absolute bottom-5 text-xs">{open+1} / {gallery.length}</span></div>}</main> }